# Generated by Django 5.0.3 on 2024-04-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0005_auto_20190721_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.ImageField(default='category_images/default.jpg', upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_img',
            field=models.ImageField(default='restaurant_images/default.jpg', upload_to='restaurant_images/'),
        ),
    ]
