# Generated by Django 5.0.3 on 2024-04-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0006_category_category_img_restaurant_restaurant_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_images',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
    ]
